### ISSUE TITLE
The map infographic on the recently redesigned site is missing the San Jose Girl Develop Chapter, 46 cities then? 

### ISSUE THREAD

**Issue by lozandier** [girldevelopit/gdi-new-site#240]
## Description 
The map infographic (and chapters section) is missing the [San Jose Chapter](https://twitter.com/gdisjc) for some strange reason on the recently redesigned site. 

## Todo
- [ ] If the San Jose Chapter is indeed active, the homepage's SVG map infographic should reflect that by adding an additional map pointer to the appropriate region of California that points to San Jose.
- [ ] Assuming this was geocoded and normalized to match the coordinates of the map SVG, common for this sorts of thing described in task 1,  a new instance pointing to the San Jose chapter may be necessary.
- [ ] 45 cities becomes 46 cities on the headline above the SVG map infographic
- [ ] The [chapters section](https://www.girldevelopit.com/chapters) should have its California section updated to include San Jose

**Comment by juliaelman** [comment]
@lozandier thanks for posting this issue! Would you mind re-formatting it to follow the following template here #83?

**Comment by lozandier** [comment]
@juliaelman Understood; my issue has been updated to comply with the guidelines your link refers to that I understood.

**Comment by juliaelman** [comment]
@lozandier thanks for making us aware of this! I am emailing Ghaida now to get her chapter set up. :smile:

**Comment by lozandier** [comment]
@juliaelman No problem; I suggest referencing the issue template (#83 ) in the readme.md in an appropriately named new section regarding issues.

**Comment by juliaelman** [comment]
@lozandier agreed! We have have our docs setup with contribution guidelines here: http://gdi-new-site.readthedocs.org/en/latest/sources/contribution/ Feel free to open another issue (or even better, a pull request!) :+1:

**Comment by gkimbwala** [comment]
the San Jose Chapter needs to be added to the locs2.yml file. it should have been listed on between line 2015 and 2016. I think the best way to do it is to add all the information into the database and rake the database. I would have done it but I couldn't find all the information using solely using the MeetupAPI.

**Comment by amygori** [comment]
@therufs, @ChetCorey please correct me if I am not right about this, but I think the way it's set up, chapters only need to be added to the database thru the Active Admin console; there shouldn't be any need to change the seed data. The seed data was hard coded in development to give us stuff to work with (and it may be in use now to drive the tests that have since been added). Once the chapter is added to the database, the map should plot that geolocated city point without reference to the seed data. Wanted to point that out if it might be helpful, but if any contributors know any reason why updated seed data is needed, please feel free to chime in!

**Comment by therufs** [comment]
That's correct. Maybe it would be helpful to reduce the seed data somewhat
to make it clear that it's just for testing? (And improve the docs, of
course)

**Comment by Roenok** [comment]
![san-diego](https://cloud.githubusercontent.com/assets/925963/6567173/69a6f4d2-c699-11e4-8caa-6d55b04ce0c0.png)

San Diego is up on the main page; the seed data is only for testing.
